services:
  quota_middleware:
    image: ghcr.io/luler/quota-proxy:latest
    restart: always
    ports:
      - "20263:3000"
    volumes:
      - ./runtime:/app/runtime
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes